import Head from "next/head";
import Splash from "../Components/Splash/Splash";
import Navbar from "../Components/NavBar/Navbar";
import AboutMe from "../Components/AboutMe/AboutMe";
import Skills from "../Components/Skills/Skills";
import Projects from "../Components/Projects/Projects";
import ContactMe from "../Components/ContactMe/ContactMe";
import Footer from "../Components/Footer/Footer";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Yasir Ibrahim Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <Navbar />
      <Splash />
      <AboutMe />
      <Skills />
      <Projects />
      <ContactMe />
      <Footer />
    </>
  );
}
